### ISSUE TITLE
add autoscaler

### ISSUE THREAD

**Issue by stiesssh** [t2-project/kube#4]
the actual T2 has not yet any self-adaptivity. tobias rodestock created a setup with the kubernetes HPA (confere the rodestock-ba repositories).
- review tobia's HPA setup 
- integrate it as fixed part into T2, d.h.:
  - copy necessary stuff to kube repository
  - adjust documentation (very important in this case)

**Comment by delvh** [comment]
Has been implemented for a long time now.
(Although with the normal metrics instead of the custom metrics.)
